### ISSUE TITLE
"Convert to MP3" button moves out when on mobile or with non-standard resolution

### ISSUE THREAD

**Issue by Gibsol** [GameGenesis/Youtube-Video-Downloader#10]
## Example

<img width="295" alt="image" src="https://user-images.githubusercontent.com/102642008/197371730-db4c4a03-4175-4b91-b3f1-6f928602e962.png">

## Possible Solution

Since you are using Bootstrap 4 you can set up **margin-left** to the button for medium screens and above only.

### This page may be useful: 
https://stackoverflow.com/questions/37710038/bootstrap-how-to-add-bottom-margin-for-mobile-screen-only

**Comment by GameGenesis** [comment]
Hey, thank you so much for notifying me about that! I didn't test the website on taller aspect ratios, so I didn't realize the alignment was off. The changes have now been implemented :)

![yt-downloader-1](https://user-images.githubusercontent.com/52415147/199352091-b007fcb3-3b5c-48a4-b38a-b51d46de46e8.png)

![yt-downloader-2](https://user-images.githubusercontent.com/52415147/199352128-0bc3e0bd-ce76-4b77-bb27-34e1fe6de8e2.png)
