### ISSUE TITLE
Not issue, idea? Playlist exception handling?

### ISSUE THREAD

**Issue by BarryWh1te** [GameGenesis/Youtube-Video-Downloader#7]
Views.py line 142 is the location of the exception "Playlist error, playlist maybe doesn't exist" or something like that, the playlist does exist, and I'm guessing pytube needs the playlist to be further exception handled for videos that are no longer working, copyright claimed, deleted, etc.

Just something I thought you might appreciate flagging up, its probably on your list of things to do.

Cheers

**Comment by GameGenesis** [comment]
Hey, thanks for bringing that to my attention! Will put that on my to do list

**Comment by GameGenesis** [comment]
I updated the playlist exception handling and managed to find and fix a bug as well. Thanks again for the suggestion!
