### ISSUE TITLE
"Video could not be downloaded" Error on any video

### ISSUE THREAD

**Issue by annabelsandford** [GameGenesis/Youtube-Video-Downloader#8]
Unfortunately converting either to MP3 or MP4 results in a "could not be downloaded" error

**Comment by GameGenesis** [comment]
Hey, thanks for informing me! It seems that YouTube has changed their backend a bit and the library I'm using to download the video stream still isn't updated.

I implemented a temporary fix and it should work now!

**Comment by GameGenesis** [comment]
It only seems to work locally now. I'll try to see if I can fix it

**Comment by GameGenesis** [comment]
I updated and tested it on the website and it should be working now!
